### ISSUE TITLE
Evaluation module specific development tasks

### ISSUE THREAD

**Issue by tarun-goyal** [genai-apps/aggrag#5]
DRAFT: 

- [ ] need to design from completing the user eval 'feedback' loop pov
- [ ] chain forge already has a good level of evaluation flows, enough for demo. this needs to be integrated with aggrag flow
- [x] integrate more eval flows at par with evaluation iteration 2 used with aggrag nvestigator + HM aggrag evals (?)
- [ ] design eval module from latest bookmarked research / academic resources

**Comment by tarun-goyal** [comment]
Moving it to backlog as one task under this is completed and remaning ones are not planned for now.
